export const testCases = [
  { id: 'TC-MOBILE-AI-01', module: 'AI', name: 'Open AI Chat' },
  { id: 'TC-MOBILE-AI-02', module: 'AI', name: 'Send AI Message' },
  { id: 'TC-MOBILE-AI-03', module: 'AI', name: 'Receive AI Response' },
  { id: 'TC-MOBILE-AI-04', module: 'AI', name: 'Clear AI History' },
  { id: 'TC-MOBILE-AI-05', module: 'AI', name: 'Voice Input to AI' },
  { id: 'TC-MOBILE-AUTH-01', module: 'AUTH', name: 'Invalid Login' },
  { id: 'TC-MOBILE-AUTH-02', module: 'AUTH', name: 'Valid Login' },
  { id: 'TC-MOBILE-AUTH-03', module: 'AUTH', name: 'Logout' },
  { id: 'TC-MOBILE-AUTH-04', module: 'AUTH', name: 'Reset Password' },
  { id: 'TC-MOBILE-AUTH-05', module: 'AUTH', name: 'Sign Up New User' },
  { id: 'TC-MOBILE-PROF-01', module: 'PROFILE', name: 'View Profile' },
  { id: 'TC-MOBILE-PROF-02', module: 'PROFILE', name: 'Edit Profile Info' },
  { id: 'TC-MOBILE-PROF-03', module: 'PROFILE', name: 'Change Password' },
  { id: 'TC-MOBILE-PROF-04', module: 'PROFILE', name: 'Upload Avatar' },
  { id: 'TC-MOBILE-PROF-05', module: 'PROFILE', name: 'Delete Account' },
  { id: 'TC-MOBILE-DASH-01', module: 'DASHBOARD', name: 'View Dashboard' },
  { id: 'TC-MOBILE-DASH-02', module: 'DASHBOARD', name: 'Pull to Refresh' },
  { id: 'TC-MOBILE-DASH-03', module: 'DASHBOARD', name: 'Click Item Widget' },
  { id: 'TC-MOBILE-DASH-04', module: 'DASHBOARD', name: 'Scroll Dashboard' },
  { id: 'TC-MOBILE-DASH-05', module: 'DASHBOARD', name: 'Filter Dashboard Data' },
  { id: 'TC-MOBILE-SETT-01', module: 'SETTINGS', name: 'Open Settings' },
  { id: 'TC-MOBILE-SETT-02', module: 'SETTINGS', name: 'Toggle Dark Mode' },
  { id: 'TC-MOBILE-SETT-03', module: 'SETTINGS', name: 'Change Language' },
  { id: 'TC-MOBILE-SETT-04', module: 'SETTINGS', name: 'Notification Toggles' },
  { id: 'TC-MOBILE-SETT-05', module: 'SETTINGS', name: 'About App Screen' },
  { id: 'TC-MOBILE-NOTIF-01', module: 'NOTIFICATIONS', name: 'Receive Push Notif' },
  { id: 'TC-MOBILE-NOTIF-02', module: 'NOTIFICATIONS', name: 'Mark Notif as Read' },
  { id: 'TC-MOBILE-NOTIF-03', module: 'NOTIFICATIONS', name: 'Clear All Notifs' },
  { id: 'TC-MOBILE-NOTIF-04', module: 'NOTIFICATIONS', name: 'Click Notif to Navigate' }
];
